In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from pandas import Series, DataFrame

In [18]:
# Introduction to Panda Data Structure.

In [19]:
#Series.:- one dimensinal array associated with its index like dictionary. of same data types.

In [20]:
obj = pd.Series([4,7,-5,3])

In [21]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [23]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [25]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [26]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [27]:
obj2['a']

-5

In [29]:
obj2[['b','d','c']]

b    7
d    4
c    3
dtype: int64

In [30]:
# performing mathematical and logical operation on a series.

In [31]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [32]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [33]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [34]:
'b' in obj2

True

In [36]:
'e' in obj2

False

In [37]:
# we can create a series by passing dictionary in it.

In [38]:
sdata = {'delhi':3500,'mumbai':71000,'varanasi':16000,'meerut':5000}

In [39]:
obj3 = pd.Series(sdata)

In [40]:
obj3  

delhi        3500
mumbai      71000
varanasi    16000
meerut       5000
dtype: int64

In [41]:
city  = ['bengluru','mumbai','varanasi','meerut']

In [42]:
obj4 = pd.Series(sdata, index = city)

In [43]:
obj4 # here the value of bengluru is missing. NaN == 'not a number'

bengluru        NaN
mumbai      71000.0
varanasi    16000.0
meerut       5000.0
dtype: float64

In [44]:
# missing values can be detected by using isnull or notnull functions of panda.

In [45]:
pd.isnull(obj4)

bengluru     True
mumbai      False
varanasi    False
meerut      False
dtype: bool

In [46]:
pd.notnull(obj4)

bengluru    False
mumbai       True
varanasi     True
meerut       True
dtype: bool

In [47]:
obj4.isnull()

bengluru     True
mumbai      False
varanasi    False
meerut      False
dtype: bool

In [48]:
# series automaticcaly align by index label in airthmatics operations.

In [49]:
obj3

delhi        3500
mumbai      71000
varanasi    16000
meerut       5000
dtype: int64

In [50]:
obj4

bengluru        NaN
mumbai      71000.0
varanasi    16000.0
meerut       5000.0
dtype: float64

In [52]:
obj3 + obj4  # indexes are sorted here...

bengluru         NaN
delhi            NaN
meerut       10000.0
mumbai      142000.0
varanasi     32000.0
dtype: float64

In [53]:
obj4.name = 'population'

In [54]:
obj4.index.name = 'city'

In [55]:
obj4

city
bengluru        NaN
mumbai      71000.0
varanasi    16000.0
meerut       5000.0
Name: population, dtype: float64

In [56]:
# index series can be altered.

In [57]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [58]:
obj.index = ['sivar','gaurav','saeed','singh']

In [59]:
obj

sivar     4
gaurav    7
saeed    -5
singh     3
dtype: int64

In [1]:
# DataFrames:- it represents a rectangular table of data contaning an orderd collection of columns. of diffrent data types or values.

In [7]:
data = {'state': ['oho','oho','oho','nevada','nevada','nevada'] , 'year': [2000,2001,2002,2001,2002,2003],'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}

In [8]:
frame =  pd.DataFrame(data)

In [9]:
frame

state  year  pop
0     oho  2000  1.5
1     oho  2001  1.7
2     oho  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  nevada  2003  3.2

In [13]:
frame.head() # it select only first five rows.

state  year  pop
0     oho  2000  1.5
1     oho  2001  1.7
2     oho  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [14]:
# we can specify a sequence of column.

In [15]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000     oho  1.5
1  2001     oho  1.7
2  2002     oho  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  nevada  3.2

In [16]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index = ['one','two','three','four','five','six']) 

#if we specify a column that is not in dict. it will appear with missing values in result

In [17]:
frame2

year   state  pop debt
one    2000     oho  1.5  NaN
two    2001     oho  1.7  NaN
three  2002     oho  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN
six    2003  nevada  3.2  NaN

In [18]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [19]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [20]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [22]:
frame2.loc['three'] # it retrived the rows  by position or rows.

year     2002
state     oho
pop       3.6
debt      NaN
Name: three, dtype: object

In [23]:
frame2.debt = 16.5  # we can also do the same by "frame2['debt'] = 16.5"

In [24]:
frame2

year   state  pop  debt
one    2000     oho  1.5  16.5
two    2001     oho  1.7  16.5
three  2002     oho  3.6  16.5
four   2001  nevada  2.4  16.5
five   2002  nevada  2.9  16.5
six    2003  nevada  3.2  16.5

In [25]:
frame2['debt'] = np.arange(6)

In [26]:
frame2

year   state  pop  debt
one    2000     oho  1.5     0
two    2001     oho  1.7     1
three  2002     oho  3.6     2
four   2001  nevada  2.4     3
five   2002  nevada  2.9     4
six    2003  nevada  3.2     5

In [27]:
val = pd.Series([-1.2,-1.5,-1.7], index = ['two','four','five'])

In [28]:
frame2['debt'] = val   # for more detail see page no. 131 as ***

In [29]:
frame2

year   state  pop  debt
one    2000     oho  1.5   NaN
two    2001     oho  1.7  -1.2
three  2002     oho  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [32]:
frame2['eastern'] = frame2.state == 'oho'   # for more details see page no. 132 as ***

In [33]:
frame2

year   state  pop  debt  eastern
one    2000     oho  1.5   NaN     True
two    2001     oho  1.7  -1.2     True
three  2002     oho  3.6   NaN     True
four   2001  nevada  2.4  -1.5    False
five   2002  nevada  2.9  -1.7    False
six    2003  nevada  3.2   NaN    False

In [34]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [35]:
pop = {'nevada' : {2001: 2.4, 2002: 2.9}, 'ohio' :{2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [15]:
frame3 = pd.DataFrame(pop)  # for more details see page no.132 as **

NameError: name 'pop' is not defined

In [37]:
frame3

nevada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [38]:
frame3.T   # we can transpose it by .T method of numpy

2000  2001  2002
nevada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [45]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

AttributeError: 'list' object has no attribute 'astype'

In [46]:
pdata = {'ohio': frame3['ohio'][:-1], 'nevada': frame3['nevada'][:2]}

In [48]:
pd.DataFrame(pdata)

ohio  nevada
2000   1.5     NaN
2001   1.7     2.4

In [49]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [50]:
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [51]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [52]:
frame2.values

array([[2000, 'oho', 1.5, nan, True],
       [2001, 'oho', 1.7, -1.2, True],
       [2002, 'oho', 3.6, nan, True],
       [2001, 'nevada', 2.4, -1.5, False],
       [2002, 'nevada', 2.9, -1.7, False],
       [2003, 'nevada', 3.2, nan, False]], dtype=object)

In [53]:
# Index Objects

In [4]:
obj = pd.Series(range(3), index = ['a','b','c'])

In [5]:
index = obj.index

In [6]:
index

Index(['a', 'b', 'c'], dtype='object')

In [7]:
index[1:]

Index(['b', 'c'], dtype='object')

In [8]:
index[1] = 'd'  # it is immutable.

TypeError: Index does not support mutable operations

In [9]:
labels = pd.Index(np.arange(3))

In [10]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [11]:
obj2 = pd.Series([-1.5,-2.5,0], index = labels)

In [12]:
obj2

0   -1.5
1   -2.5
2    0.0
dtype: float64

In [13]:
obj2.index is labels

True

In [16]:
# pandas Index can contain duplicate elements.

In [17]:
dup_labels = pd.Index(['hel','bel','hel','bel'])

In [18]:
dup_labels

Index(['hel', 'bel', 'hel', 'bel'], dtype='object')

In [19]:
# ESSENTIAL FUNCTIONALITY:-

In [20]:
# 1. Reindexing:- the method in panda which create a new object with new provided index.

In [21]:
obj = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])

In [22]:
obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [23]:
obj.reindex(['a','b','c','d','e','f'])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
dtype: float64

In [24]:
obj3 = pd.Series(['blue','purple','red'], index = [0,2,4])

In [25]:
obj3

0      blue
2    purple
4       red
dtype: object

In [28]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4       red
5       red
dtype: object

In [30]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns= ['ohio','Texas','california'])

In [31]:
frame

ohio  Texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [32]:
frame2= frame.reindex(['a','b','c','d'])  # row is reindexd

In [33]:
frame2

ohio  Texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [34]:
states = ['UP','BIHAR','WB']

In [36]:
frame.reindex(columns=states, fill_value='23') # here columns will be reindexed.

UP BIHAR  WB
a  23    23  23
c  23    23  23
d  23    23  23

In [37]:
# Dropping Entries from Axis.

In [38]:
obj = pd.Series(np.arange(5.0), index= ['a','b','c','d','e'])

In [39]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [40]:
new_obj = obj.drop('c')

In [41]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [46]:
obj.drop(['d', 'c'])  # this function doesn't delete the actual value of a series.

a    0.0
b    1.0
e    4.0
dtype: float64

In [47]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [48]:
# for a data frame.

In [50]:
data = pd.DataFrame(np.arange(16).reshape(4,4), index= ['ohio','colrado','utah','ny'], columns= ['one','two','thre','four'])

In [51]:
data

one  two  thre  four
ohio       0    1     2     3
colrado    4    5     6     7
utah       8    9    10    11
ny        12   13    14    15

In [52]:
data.drop(['ohio','colrado'])

one  two  thre  four
utah    8    9    10    11
ny     12   13    14    15

In [54]:
data.drop(['thre','four'], axis='columns') # We can pass axis = 1 also, to drop columns. 

one  two
ohio       0    1
colrado    4    5
utah       8    9
ny        12   13

In [55]:
obj.drop('c', inplace=True) # this will permanently drop the data."in-place"

In [56]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [57]:
# INDEXING , SELECTING and FILTERING  :-

In [58]:
obj = pd.Series(np.arange(4.0), index= ['a','b','c','d'])

In [59]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [60]:
obj['b']

1.0

In [61]:
obj[1]

1.0

In [62]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [63]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [64]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [65]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [66]:
obj[2:4]  # Slicing

c    2.0
d    3.0
dtype: float64

In [67]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [68]:
obj['b':'c'] = 5 # Assinging the value

In [69]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [70]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index= ['ohio','colrado','texas','NY'], columns= ['one','two','three','four'])

In [71]:
data

one  two  three  four
ohio       0    1      2     3
colrado    4    5      6     7
texas      8    9     10    11
NY        12   13     14    15

In [72]:
data['two']

ohio        1
colrado     5
texas       9
NY         13
Name: two, dtype: int32

In [74]:
data[['three','one']]

three  one
ohio         2    0
colrado      6    4
texas       10    8
NY          14   12

In [75]:
data[:2] 

one  two  three  four
ohio       0    1      2     3
colrado    4    5      6     7

In [76]:
data[data['three'] > 5]

one  two  three  four
colrado    4    5      6     7
texas      8    9     10    11
NY        12   13     14    15

In [77]:
data < 5

one    two  three   four
ohio      True   True   True   True
colrado   True  False  False  False
texas    False  False  False  False
NY       False  False  False  False

In [78]:
data[data < 5] = 0

In [79]:
data

one  two  three  four
ohio       0    0      0     0
colrado    0    5      6     7
texas      8    9     10    11
NY        12   13     14    15

In [80]:
# Selection with loc and iloc :- used for selecting specific row and columns. iloc stand for integer location.

In [81]:
data.loc['colrado', ['two','three']]

two      5
three    6
Name: colrado, dtype: int32

In [82]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: texas, dtype: int32

In [83]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: texas, dtype: int32

In [84]:
data.iloc[[1,2], [3,0,1]]

four  one  two
colrado     7    0    5
texas      11    8    9

In [87]:
data.loc[: 'texas','two']

ohio       0
colrado    5
texas      9
Name: two, dtype: int32

In [88]:
data.iloc[:, :3][data.three > 5]

one  two  three
colrado    0    5      6
texas      8    9     10
NY        12   13     14

In [89]:
# Integer Indexes:- 

In [90]:
ser = pd.Series(np.arange(3.))

In [91]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [92]:
ser[-1]  # it generates error (key error). 

KeyError: -1

In [93]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])

In [94]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [96]:
ser2[-1]  # here it doesn't give error because of with non-integer index there is no posiblity of ambiguity.

2.0

In [97]:
ser[:1]

0    0.0
dtype: float64

In [98]:
ser.loc[:1]  # loc function gives the value upto the given index.

0    0.0
1    1.0
dtype: float64

In [99]:
ser.iloc[:1]

0    0.0
dtype: float64

In [100]:
# Airthmatic And Data Alingment.

In [101]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index= ['a','c','d','e'])

In [102]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.2], index= ['a','c','e','f','g'])

In [103]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [104]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.2
dtype: float64

In [105]:
s1 + s2 # the label location that doesn't overlap is automatically filled with null vlues. 

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [106]:
# in case of dataframe alingment performed in both row and column. 

In [107]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'), index= ['ohio','texas','colorado'])

In [108]:
df2 = pd.DataFrame(np.arange(12).reshape(4,3), columns=list('bde'), index= ['utah','ohio','texas','oregeon'])

In [109]:
df1

b  c  d
ohio      0  1  2
texas     3  4  5
colorado  6  7  8

In [110]:
df2

b   d   e
utah     0   1   2
ohio     3   4   5
texas    6   7   8
oregeon  9  10  11

In [111]:
df1 + df2 # the 'c' and 'e'  columns are not found in both data frame so it will be filled with NaN.(NOT A NUMBER)

b   c     d   e
colorado  NaN NaN   NaN NaN
ohio      3.0 NaN   6.0 NaN
oregeon   NaN NaN   NaN NaN
texas     9.0 NaN  12.0 NaN
utah      NaN NaN   NaN NaN

In [112]:
# if we add two dataframe with no common rows and column the result will be all null.

In [113]:
# Airthmatis method with fill values.

In [114]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns= list('abcd'))

In [115]:
df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns= list('abcde'))

In [116]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [117]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [118]:
df2.loc[1,'b'] = np.nan

In [119]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [120]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [121]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [123]:
df1.reindex(columns= df2.columns, fill_value = 0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [124]:
# Operations between DataFrame and Series:-

In [125]:
arr = np.arange(12.).reshape(3,4)

In [126]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [127]:
arr[0]

array([0., 1., 2., 3.])

In [128]:
arr - arr[0]  # see page no 150 for more details.

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [129]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3), columns = list('bde'))

In [130]:
series = frame.iloc[0]

In [131]:
series

b    0.0
d    1.0
e    2.0
Name: 0, dtype: float64

In [132]:
frame

b     d     e
0  0.0   1.0   2.0
1  3.0   4.0   5.0
2  6.0   7.0   8.0
3  9.0  10.0  11.0

In [133]:
frame - series

b    d    e
0  0.0  0.0  0.0
1  3.0  3.0  3.0
2  6.0  6.0  6.0
3  9.0  9.0  9.0

In [134]:
series2 = pd.Series(np.arange(3), index= ['b','e','f'])

In [135]:
frame + series2

b   d     e   f
0  0.0 NaN   3.0 NaN
1  3.0 NaN   6.0 NaN
2  6.0 NaN   9.0 NaN
3  9.0 NaN  12.0 NaN

In [136]:
series3 = frame['d']

In [137]:
frame

b     d     e
0  0.0   1.0   2.0
1  3.0   4.0   5.0
2  6.0   7.0   8.0
3  9.0  10.0  11.0

In [138]:
series

b    0.0
d    1.0
e    2.0
Name: 0, dtype: float64

In [139]:
series3

0     1.0
1     4.0
2     7.0
3    10.0
Name: d, dtype: float64

In [140]:
frame.sub(series3, axis='index')

b    d    e
0 -1.0  0.0  1.0
1 -1.0  0.0  1.0
2 -1.0  0.0  1.0
3 -1.0  0.0  1.0

In [141]:
# Function Application And Mapping:-

In [6]:
frame = pd.DataFrame(np.random.randn(4,3), columns= list('bde'), index= ['utah','ohio','texas','oregeon'])

In [7]:
frame

b         d         e
utah     1.168005  0.973002  0.345565
ohio     1.080990 -1.153062  1.120883
texas   -0.800109  1.403199 -1.013837
oregeon -2.146777  1.137909 -0.244966

In [8]:
np.abs(frame)

b         d         e
utah     1.168005  0.973002  0.345565
ohio     1.080990  1.153062  1.120883
texas    0.800109  1.403199  1.013837
oregeon  2.146777  1.137909  0.244966

In [9]:
f = lambda x: x.max() - x.min()

In [10]:
frame.apply(f)  # dataframe 'apply' method performs like a one dimensional array to each row and column. it is in column in frame

b    3.314782
d    2.556261
e    2.134720
dtype: float64

In [11]:
frame.apply(f, axis= 'columns')   # for row.

utah       0.822441
ohio       2.273945
texas      2.417036
oregeon    3.284686
dtype: float64

In [12]:
# the function passed to apply can return series with multiple values.

In [13]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [14]:
frame.apply(f)

b         d         e
min -2.146777 -1.153062 -1.013837
max  1.168005  1.403199  1.120883

In [15]:
# we can also use element wise python function 

In [16]:
format = lambda x: '%.2f' % x

In [17]:
frame.applymap(format)  # Series ahs map method for applying an element wise function.

b      d      e
utah      1.17   0.97   0.35
ohio      1.08  -1.15   1.12
texas    -0.80   1.40  -1.01
oregeon  -2.15   1.14  -0.24

In [18]:
frame['e'].map(format)

utah        0.35
ohio        1.12
texas      -1.01
oregeon    -0.24
Name: e, dtype: object

In [19]:
# Sorting And Ranking:-

In [20]:
obj = pd.Series(range(4), index= ['d','a','b','c'])

In [21]:
obj.sort_index() # sort_index method sort the  index

a    1
b    2
c    3
d    0
dtype: int64

In [22]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index= ['three','two'], columns= ['d','a','b','c'])

In [23]:
frame

d  a  b  c
three  0  1  2  3
two    4  5  6  7

In [24]:
frame.sort_index()

d  a  b  c
three  0  1  2  3
two    4  5  6  7

In [25]:
frame.sort_index(axis= 1) # it will sort the columns.

a  b  c  d
three  1  2  3  0
two    5  6  7  4

In [26]:
# the data is sorted in ascending order by default. but it can be sorted in descending order too.

In [27]:
frame.sort_index(axis = 1, ascending= False)

d  c  b  a
three  0  3  2  1
two    4  7  6  5

In [28]:
# we can sort the values by using method sort_values

In [29]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [30]:
# the missing values is sorted to the end of all the values by-default

In [31]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [32]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [33]:
frame.sort_values( by= 'a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [34]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [36]:
frame.sort_values()  # we have to pass the columns in 'by' option in sort values.

TypeError: sort_values() missing 1 required positional argument: 'by'

In [37]:
# RANKING:-

In [38]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [39]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [40]:
obj.rank(method= 'first') # rank can also be assigned 

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [44]:
obj.rank(ascending= False, method='max')   # assign tie values the amximum rank in the group.

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [45]:
frame= pd.DataFrame({'b': [4.3,7,-3,2], 'a': [0,1,0,1], 'c': [-2,5,8,-2.5]})

In [46]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [47]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [48]:
# Axis indexes with duplicate lables.

In [49]:
obj = pd.Series(range(5), index= ['a','a','b','b','c'])

In [50]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [51]:
obj.index.is_unique

False

In [52]:
obj['c']

4

In [53]:
obj['b']

b    2
b    3
dtype: int64

In [54]:
df = pd.DataFrame(np.random.randn(4,3), index= ['a','a','b','b'])

In [55]:
df

0         1         2
a  2.849108  1.182329  1.571062
a  1.601524 -0.169258  1.189445
b -0.563394 -0.251320  0.621802
b -0.633047  0.759810 -1.711545

In [56]:
df.loc['b']

0        1         2
b -0.563394 -0.25132  0.621802
b -0.633047  0.75981 -1.711545

In [57]:
# Computing Discriptive Statistics:-

In [60]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]], index= ['a','b','c','d'], columns= ['one','two'])

In [61]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [62]:
df.sum()  # it add the elements in column wise.

one    9.25
two   -5.80
dtype: float64

In [63]:
df.sum(axis= 'columns')  #

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [64]:
df.mean(axis= 'columns', skipna= False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [65]:
df.idxmax()

one    b
two    d
dtype: object

In [66]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [67]:
df.describe() # it produces multiple summary  statics at a time.

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [68]:
#on non-numeric data it produces alternative summary statistics,

In [69]:
obj = pd.Series(['a','a','b','c'] * 4)

In [70]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [71]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [72]:
# Correlation and Covariance :-

In [2]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'